# Configuration des demi-groupes par matière
filters:
  "apprentissage par renforcement": A
  "patrons de conception logicielle": B
  "modélisation de problèmes et Optimisation combinatoire": B
  "réseaux de neurones avancés": B
  "test, intégration et déploiement logiciels": B
# URL du calendrier original
ical_url: "http://edt-v2.univ-nantes.fr/calendar/ics?timetables[0]=93154"
